[font-overrides]
1 = numeric
2 = font3
3 = font1
4 = font2
5 = font5


[ttf-fonts]
file1 = "wenquanyi_9pt.pcf"
file1-antialias = false
file1-bitmap-size = 12
file1-double-pixel = true

file2 = "Galmuri9.ttf"
file2-antialias = false
file2-bitmap-size = 12
file2-double-pixel = true
file2-lang-priority = "ko,ja"

;file3 = "x12y12pxMaruMinya.ttf"
;file3-antialias = false
;file3-bitmap-size = 12
;file3-double-pixel = true
;file3-lang-priority = "ja"

file3 = "unifont-15.0.01.otf"
file3-antialias = false
file3-bitmap-size = 16
file3-double-pixel = false

file4 = "NotoEmoji-Regular.ttf"
file4-antialias = false
